### ISSUE TITLE
Upgrade version helm

### ISSUE THREAD

**Issue by JoniSanchez** [jshimko/kube-tools-aws#1]
would it be possible for you to upload the image back to dockerhub with the new ones? The helm versions have several bugs. 

thanks!

**Comment by jshimko** [comment]
Didn't realize anyone else was using this.  I've been manually building for myself.  :)

All set!

```sh
kubectl 1.18.3
helm 3.2.1
helm-s3 plugin 0.9.2
aws-iam-authenticator 1.16.8
```

https://circleci.com/gh/jshimko/kube-tools-aws/24

`jshimko/kube-tools-aws:3.3.0`

or 

`jshimko/kube-tools-aws:latest`

https://hub.docker.com/repository/docker/jshimko/kube-tools-aws/tags
