### ISSUE TITLE
Use awscli v2

### ISSUE THREAD

**Issue by nesl247** [jshimko/kube-tools-aws#4]

**Comment by jshimko** [comment]
Can you elaborate on this?  Also, pull requests are welcome!

**Comment by nesl247** [comment]
Sure. The currently used version of the awscli in this docker image is 1.x, while 2.x is the latest. 1.x is maintained for BC purposes it looks like, and prints a warning on every command.

I actually ended up creating my own image, so I appreciate the quick response, however, we'll use our internally maintained version instead.

Feel free to close this if this isn't something you'd want to track for your image.

Thanks!

**Comment by jshimko** [comment]
This is fixed.  aws-cli v2 is now the default as of 3.6.0.

```sh
docker run --rm -it jshimko/kube-tools-aws:3.6.0 aws --version

# aws-cli/2.1.29 Python/3.8.8 Linux/4.19.121-linuxkit exe/x86_64.alpine.3 prompt/off
```
