### ISSUE TITLE
Upgrading to latest versions of terraform?

### ISSUE THREAD

**Issue by timurista** [jshimko/kube-tools-aws#5]
How would you or can you upgrade docker image to use latest terraform version 0.13 etc when new versions are available.
Thanks

**Comment by jshimko** [comment]
Terraform isn't a direct dependency of this image, so you'd have to do that in your own custom build.  You can do that in a few ways... 

You could create a new image based on this one with a Dockerfile like this...

```Dockerfile
FROM jshimko/kube-tools-aws:latest

RUN apk add terraform
```

Or you could clone/fork this repo and add it to the base Dockerfile and then maintain your own build.  Either way is pretty much the same amount of effort.  It just depends on how much you want to manage your own image.

**Comment by jshimko** [comment]
Also, see this example of installing Terraform 0.13 on Alpine Linux...

https://github.com/broadinstitute/docker-terraform/blob/master/Dockerfile

**Comment by jshimko** [comment]
Or... 

Use the official Terraform image as a starting point and copy the stuff you want from my image.

https://github.com/hashicorp/terraform/blob/master/Dockerfile

**Comment by timurista** [comment]
thanks! this will work for me
